### ISSUE TITLE
What if I don't have any window?

### ISSUE THREAD

**Issue by felipecrs** [paymoapp/electron-shutdown-handler#4]
I have [an Electron app](https://github.com/felipecrs/clipboard-sync) that doesn't have any window, only a tray icon.

Unfortunately, [tray icons](https://www.electronjs.org/docs/latest/api/tray) do not have have a `getNativeWindowHandle()` method to supply to `ElectronShutdownHandler.setWindowHandle`.

Do you have any ideas on how can I still add the shutdown handler to my app?

**Comment by gergof** [comment]
Hi! Unfortunately you have to have a window OR a console application (not supported by this package, and not the case), otherwise you can't intercept the shutdown signal (see: https://learn.microsoft.com/en-us/windows/win32/shutdown/wm-queryendsession). This is how Windows works.

But you can create a hidden electron window from which you can get the handle.
The other solution would involve some C++ code where you would create a hidden window directly using winapi code.
