### ISSUE TITLE
setWindowHandle is not a function

### ISSUE THREAD

**Issue by Thiru-Malai** [paymoapp/electron-shutdown-handler#7]
Is it possible to solve this error. It saying setWindowHandle is not a function and it's undefined.
Windows 11

**Comment by morningf** [comment]
+1

**Comment by gergof** [comment]
Hi! Are you using some kind of bundler? Vite for example messed up the imports for me as well. 
Check out this, it's probably the same issue: https://github.com/paymoapp/node-active-window/issues/2#issuecomment-1720943964

Basically:
- you have to tell vite/your bundler to not bundle your module (treat it as an external module)
- you have to use CJS interoperability, since the module is bundled as CJS.

We have a config like this when bundling our electron main with vite:
```ts
import { builtinModules } from 'module';
import { defineConfig } from 'vite';

export default defineConfig({
	root: __dirname,
	envDir: process.cwd(),
	build: {
		outDir: '../../dist_electron/electron/main',
		emptyOutDir: true,
		sourcemap: true,
		target: 'node16',
		lib: {
			entry: 'index.ts',
			formats: ['cjs']
		},
		rollupOptions: {
			external: [
				'@paymoapp/electron-shutdown-handler', // this is important
				...builtinModules.flatMap(p => [p, `node:${p}`])
			],
			output: {
				entryFileNames: '[name].cjs',
				interop: 'auto' // and this is important
			}
		}
	}
});
```

**Comment by Thiru-Malai** [comment]
No I wasn't using any bundler.

**Comment by gergof** [comment]
Could you please provide your environment then? And as a simple debugging step, please do the following:

```ts
import ElectronShutdownHandler from '@paymoapp/electron-shutdown-handler';

console.log(ElectronShurdownHandler);
```

**Comment by Thiru-Malai** [comment]
Currently I don't have the project with me right now @gergof.

**Comment by wellojbk** [comment]
Use this
`const ElectronShutdownHandler = require('@paymoapp/electron-shutdown-handler').default`
